const express = require('express');
const webpush = require('web-push');
const { query } = require('../config/database');
const { requireAuth } = require('../middleware/auth');
const router = express.Router();
let vapidReady = false;
if (process.env.VAPID_PUBLIC_KEY && process.env.VAPID_PRIVATE_KEY) { try { webpush.setVapidDetails('mailto:' + (process.env.VAPID_EMAIL || 'no-reply@ippmify.com'), process.env.VAPID_PUBLIC_KEY, process.env.VAPID_PRIVATE_KEY); vapidReady = true; } catch (e) { console.error('[Push] VAPID invalido:', e.message); } }
let tableReady = false;
async function ensureTable() { if (tableReady) { return; } await query('CREATE TABLE IF NOT EXISTS push_subscriptions (id SERIAL PRIMARY KEY, user_id UUID NOT NULL, endpoint TEXT NOT NULL UNIQUE, p256dh TEXT NOT NULL, auth_key TEXT NOT NULL, user_agent TEXT, created_at TIMESTAMPTZ DEFAULT NOW())'); await query('CREATE INDEX IF NOT EXISTS push_subs_user_idx ON push_subscriptions(user_id)'); tableReady = true; }
router.get('/vapid-key', (req, res) => { if (!vapidReady) { return res.status(503).json({ error: 'VAPID nao configurado no servidor.' }); } res.json({ publicKey: process.env.VAPID_PUBLIC_KEY }); });
router.post('/subscribe', requireAuth, async (req, res) => { const { endpoint, keys, userAgent } = req.body || {}; if (!endpoint || !keys || !keys.p256dh || !keys.auth) { return res.status(400).json({ error: 'Subscription invalida' }); } try { await ensureTable(); await query('INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth_key, user_agent) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (endpoint) DO UPDATE SET user_id=$1, p256dh=$3, auth_key=$4, user_agent=$5', [req.user.id, endpoint, keys.p256dh, keys.auth, userAgent || null]); res.json({ success: true }); } catch (e) { console.error('[Push] subscribe:', e.message); res.status(500).json({ error: 'Erro ao salvar' }); } });
router.delete('/unsubscribe', requireAuth, async (req, res) => { try { await ensureTable(); await query('DELETE FROM push_subscriptions WHERE user_id=$1 AND endpoint=$2', [req.user.id, (req.body || {}).endpoint]); res.json({ success: true }); } catch (e) { res.status(500).json({ error: 'Erro ao remover' }); } });
router.post('/test', requireAuth, async (req, res) => { try { const n = await sendPushToUser(req.user.id, 'IPPMIFY', 'Notificacoes funcionando!', { tag: 'ippmify-test' }); res.json({ success: true, sent: n }); } catch (e) { res.status(500).json({ error: e.message }); } });
async function sendPushToUser(userId, title, body, extra) { if (!vapidReady || !userId) { return 0; } try { await ensureTable(); const r = await query('SELECT * FROM push_subscriptions WHERE user_id=$1', [userId]); const subs = r.rows || []; if (!subs.length) { return 0; } const payload = JSON.stringify(Object.assign({ title: title, body: body, url: '/' }, extra || {})); const dead = []; let ok = 0; await Promise.all(subs.map(async (s) => { try { await webpush.sendNotification({ endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth_key } }, payload); ok++; } catch (e) { if (e.statusCode === 410 || e.statusCode === 404) { dead.push(s.endpoint); } else { console.error('[Push] envio:', e.message); } } })); if (dead.length) { await query('DELETE FROM push_subscriptions WHERE endpoint = ANY($1)', [dead]); } return ok; } catch (e) { console.error('[Push] sendPushToUser:', e.message); return 0; } }
module.exports = router;
module.exports.sendPushToUser = sendPushToUser;
